steps:



# - name: 'docker.io/library/python:3.10'
#   entrypoint: /bin/sh
#   # Run pip install and pytest in the same build step
#   # (pip packages won't be preserved in future steps!)
#   args: [-c, 'pip install -r requirements.txt']
#   dir: 'function1'

  #cloud function ci cd
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'deploy', 'cicd-function1','--gen2', '--trigger-http',
         '--runtime', 'python310', '--entry-point', 'hello_http',
         '--region','us-central1','--run-service-account','${_SERVICE_ACCOUNT}',
         '--max-instances','2','--memory','128Mi',
         '--timeout','3600']
  dir: 'function1/cloud-function'


#gcloud functions deploy function2 --gen2 --trigger-http --runtime=python310 --entry-point=hello_http --region=us-central1 --run-service-account=cloud-functions@denem-344611.iam.gserviceaccount.com --max-instances=2 --memory=128M --timeout=3600
  #airflow ci/cd

